============================= test session starts =============================
platform win32 -- Python 3.13.0, pytest-7.4.4, pluggy-1.0.0 -- C:\Users\vlkra\miniconda3\envs\hw_3\python.exe
cachedir: .pytest_cache
rootdir: C:\Users\vlkra\dev\itmo_python\hw_3
collecting ... collected 9 items

src/matrix_mixin_tests.py::test_matrix_operations PASSED                 [ 11%]
src/matrix_mixin_tests.py::test_matrix_add PASSED                        [ 22%]
src/matrix_mixin_tests.py::test_matrix_sub PASSED                        [ 33%]
src/matrix_mixin_tests.py::test_matrix_mul PASSED                        [ 44%]
src/matrix_mixin_tests.py::test_matrix_matmul PASSED                     [ 55%]
src/matrix_mixin_tests.py::test_matrix_div PASSED                        [ 66%]
src/matrix_mixin_tests.py::test_matrix_file PASSED                       [ 77%]
src/matrix_mixin_tests.py::test_matrix_str PASSED                        [ 88%]
src/matrix_mixin_tests.py::test_matrix_props PASSED                      [100%]

============================== warnings summary ===============================
src/matrix_mixin_tests.py::test_matrix_operations
  C:\Users\vlkra\dev\itmo_python\hw_3\src\matrix_mixin.py:42: RuntimeWarning: divide by zero encountered in divide
    return self.__class__(np.divide(self.data, other.data))

src/matrix_mixin_tests.py::test_matrix_operations
  C:\Users\vlkra\dev\itmo_python\hw_3\src\matrix_mixin.py:42: RuntimeWarning: invalid value encountered in divide
    return self.__class__(np.divide(self.data, other.data))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
======================== 9 passed, 2 warnings in 0.09s ========================
